Trade:
  #交易双方确认后的等待时间（单位秒）
  Wait-Time: 5

  #什么方式可以发起交易
  Triggers:
    #蹲下加右键快捷发起交易
    Shift-Right-Click: true

  #安全处理
  Safe:
    #是否开启交易期间玩家不受会伤害
    Damage: false
    #交易期间玩家是否阻止移动、被推动等
    Move: false

  #阻止特定物品进行交易
  Item-BlackList:
    #是否开启黑名单
    Enable: false
    #黑名单物品名称
    Name:
      - "XXX"
    #黑名单物品Lore
    Lore:
      - "任意一条符合将无法交易"
      - "禁止交易"

texts:
  request: "${prefix}§7玩家 §e<name> §7向你发起交易 §a[点击接受]"

actions:
  reload:
    - 'tell-or-print: ${prefix}重载完毕'
  blacklist-item:
    - 'tell: ${prefix}§c你的物品槽有禁止交易的物品'
  drop-item:
    - 'tell: ${prefix}§c你的背包已满！多余物品已丢出'
  offline-player:
    - 'tell-or-print: ${prefix}§c玩家 <name> 不在线'
  invalid-sender:
    - 'tell-or-print: ${prefix}§c控制台不可执行该指令'
  trade-self:
    - 'tell: ${prefix}§c你不能与自己进行交易'
  trade-same:
    - 'tell-or-print: ${prefix}§c不能指定玩家与他自己交易'
  no-request:
    - 'tell: ${prefix}§c无待处理交易请求'
  request-player-offline:
    - 'tell: ${prefix}§c发起交易请求的玩家已经离线了'
  you-cancel-trade:
    - 'tell: ${prefix}你取消了交易'
  target-cancel-trade:
    - 'tell: ${prefix}对方取消了交易'
  opening-trade-gui:
    - 'tell: ${prefix}§2正在为您打开交易界面'
  request-cooldown:
    - 'tell: ${prefix}§c发起交易过于频繁，请等待一会再重试'
  request-sent:
    - 'tell: ${prefix}§7已向玩家 §e<name> §7发起交易'
  cancel-by-reload:
    - 'tell: ${prefix}§c功能重载中，交易已取消'
  no-such-request:
    - 'tell: ${prefix}§e<name> §7未曾向你发起交易请求'
