name: GoodsTrade
version: '${version}'
main: cc.sbsj.polang.goodstrade.GoodsTrade
authors: [ polang ]
description: 玩家间的物品、货币与经验等级交易
website: https://space.bilibili.com/450460661
api-version: '1.13'
softdepend: [PlaceholderAPI, Vault, PlayerPoints, ExcellentEconomy]

permissions:
  goodstrade.command.reload:
    default: op
    description: 重载插件
  goodstrade.command.trade:
    default: op
    description: 指定两个玩家进行交易
  goodstrade.command.test:
    default: op
    description: 打开测试模式，单人操作交易双方
  goodstrade.command.sendtrade:
    default: true
    description: 发送交易请求
  goodstrade.command.accept:
    default: true
    description: 接受交易请求
  goodstrade.command.toggle:
    default: true
    description: 切换交易状态
  goodstrade.command:
    default: true
    description: 使用命令的权限
commands:
  goodstrade:
    permission: goodstrade.command
    description: 交易功能主命令
    aliases: [ gt ]
