name: ${name}
main: ${group}.${name}
version: ${version}
api-version: 1.13
authors: [ polang ]
description: 简单安全的玩家物品交易插件
website: https://space.bilibili.com/450460661

permissions:
  ${name.toLowerCase()}.admin:
    default: op
  ${name.toLowerCase()}.command.trade:
    default: op
  ${name.toLowerCase()}.command.reload:
    default: op
  ${name.toLowerCase()}.command:
    default: true
  ${name.toLowerCase()}.command.sendTrade:
    default: true
  ${name.toLowerCase()}.command.accept:
    default: true
